---
repository:
  name: ansible-role-loki
  description: Ansible role for deploying loki and promtail
  topics: ansible, role, ansible-role, promtail, loki, logging

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request

...