---
- name: Assert that there is something to install
  assert:
    that: promtail_install or loki_install
    msg: "You should install promtail and/or loki"

- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/grafana/loki/releases/latest"
        method: GET
        return_content: True
        status_code: 200
        body_format: json
        validate_certs: False
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set last version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        __last_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - (promtail_version == "latest") or (loki_version == "latest")

- name: "Set loki version to {{ _latest_release.json.tag_name[1:] }}"
  set_fact:
    loki_version: "{{ __last_version }}"
  when:
    - loki_version == "latest"

- name: "Set promtail version to {{ _latest_release.json.tag_name[1:] }}"
  set_fact:
    promtail_version: "{{ __last_version }}"
  when:
    - promtail_version == "latest"

- name: "Get checksum list for loki"
  set_fact:
    __loki_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + loki_version + '/SHA256SUMS', wantlist=True) | list }}"
  run_once: True

- name: "Get checksum list for promtail"
  set_fact:
    __promtail_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + promtail_version + '/SHA256SUMS', wantlist=True) | list }}"
  run_once: True
  when:
    - loki_version != promtail_version

- name: "Assign checksum list for promtail"
  set_fact:
    __promtail_checksums: "{{ __loki_checksums }}"
  run_once: True
  when:
    - loki_version == promtail_version

- name: Get checksum for loki
  block:
    - name: "Get checksum for loki on {{ go_arch }} architecture"
      set_fact:
        __loki_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __loki_checksums }}"
      when:
        - "('loki-linux-' + go_arch + '.zip') in item"
  when:
    - loki_install

- name: Get checksum for promtail
  block:
    - name: "Get checksum for promtail on {{ go_arch }} architecture"
      set_fact:
        __promtail_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __promtail_checksums }}"
      when:
        - "('promtail-linux-' + go_arch + '.zip') in item"
  when:
    - promtail_install
