---
- name: Restart promtail
  become: True
  systemd:
    name: promtail
    state: restarted
    daemon_reload: True
  tags:
    - promtail_run
    - promtail

- name: Restart loki
  become: True
  systemd:
    name: loki
    state: restarted
    daemon_reload: True
  tags:
    - loki_run
    - loki
